(function() {var implementors = {};
implementors["fsort"] = ["impl&lt;C: <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> + <a class='trait' href='fsort/criterion/trait.Criterion.html' title='fsort::criterion::Criterion'>Criterion</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='fsort/struct.File.html' title='fsort::File'>File</a>&lt;C&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='fsort/file_collection/enum.ErrorBehavior.html' title='fsort::file_collection::ErrorBehavior'>ErrorBehavior</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='fsort/file_collection/enum.Result.html' title='fsort::file_collection::Result'>Result</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='fsort/criterion/enum.Error.html' title='fsort::criterion::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='fsort/criterion/struct.AccessDate.html' title='fsort::criterion::AccessDate'>AccessDate</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='fsort/criterion/struct.CreationDate.html' title='fsort::criterion::CreationDate'>CreationDate</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='fsort/criterion/struct.ModifyDate.html' title='fsort::criterion::ModifyDate'>ModifyDate</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='fsort/criterion/struct.FileName.html' title='fsort::criterion::FileName'>FileName</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='fsort/criterion/struct.FileSize.html' title='fsort::criterion::FileSize'>FileSize</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
